package utility;

public class SimpleStates {
	public static String[] states = {	"Alabama",
										"Alaska",
										"Arizona",
										"Arkansas",
										"California",
										"Colorado",
										"Connecticut",
										"Delaware",
										"Florida",
										"Georgia",
										"Hawaii",
										"Idaho",
										"Illinois",
										"Indiana",
										"Iowa",
										"Kansas",
										"Kentucky",
										"Louisiana",
										"Maine",
										"Maryland",
										"Massachusetts",
										"Michigan",
										"Minnesota",
										"Mississippi",
										"Missouri",
										"Montana",
										"Nebraska",
										"Nevada",
										"New Hampshire",
										"New Jersey",
										"New Mexico",
										"New York",
										"North Carolina",
										"North Dakota",
										"Ohio",
										"Oklahoma",
										"Oregon",
										"Pennsylvania",
										"Rhode Island",
										"South Carolina",
										"South Dakota",
										"Tennessee",
										"Texas",
										"Utah",
										"Vermont",
										"Virginia",
										"Washington",
										"West Virginia",
										"Wisconsin",
										"Wyoming",
										"District of Columbia",
										"Puerto Rico",
										"Guam",
										"American Samoa",
										"U.S. Virgin Islands",
										"Northern Mariana Islands"};
	
	public static String[] statesAbbreviations = {
			"AK","AL","AR","AZ","CA","CO","CT","DC","DE","FL","GA","GU","HI","IA","ID", "IL","IN","KS","KY","LA","MA","MD","ME","MH","MI","MN","MO","MS","MT","NC","ND","NE","NH","NJ","NM","NV","NY", "OH","OK","OR","PA","PR","PW","RI","SC","SD","TN","TX","UT","VA","VI","VT","WA","WI","WV","WY"
	};

}
